services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-runner
    image: infinitum-app:latest
  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: worker-runner
    image: infinitum-worker:latest
